### ISSUE TITLE
Integrate scss as main styles instead of main.css

### ISSUE THREAD

**Issue by derekwidmer** [aasmal97/visualum#2]
Currently, all styles are still all coming from the main.css file. We should switch over to use the scss files that have been written.

**Comment by derekwidmer** [comment]
To be more specific, changing things in the scss files seems to do nothing, while adjusting values in the main.css file does make changes. Something wrong with the mapping?

**Comment by aasmal97** [comment]
Nope. To map appropriately, ensure you have sass installed.

`run npm install -g sass
`
After that, if you are in the frontend directory on your command line, run 

`sass --watch ./src/scss/main.scss ./src/main.css `

The template for this command is as follows:

` sass --watch input.scss output.css`

Where input.scss is the directory location of the main.scss file, and output.css in the directory location of the main.css file. 

When you do so, any changes you make to scss will automatically map to css.
